version: '3.8'
services:
  arma3_server:
    build: .
    image: arma3-wine:latest
    container_name: arma3-wine
    ports:
     - 2401-2406:2401-2406/udp
     #- 2501-2506:2501-2506/udp
    volumes:
    # укажи путь к папке где будет сервер ARMA3 чтобы иметь возможность менять конфиг и тп
      - /path/to/arma_server/wine:/root/.wine
      - /path/to/arma_server/arma3:/arma3
      #- /path/to/arma_server/arma3/missions:/arma3/mpmissions
      #- /path/to/arma_server/arma3/configs:/arma3/configs
      #- /path/to/arma_server/arma3/mods:/arma3/mods
      #- /path/to/arma_server/arma3/servermods:/arma3/servermods
      - /path/to/arma_server/tmp/.X11-unix:/tmp/.X11-unix
      #- /path/to/arma_server/arma3/configs/profiles:/profiles
      
      
    #env_file:
    #  - /path/to/arma_server/arma3.env

    environment:
      DISPLAY: ":1"
      WINEARCH: "win32"
      ARMA_BINARY: "wine cmd /c Z:/arma3/" #путь в вайне лучше не менять, смотри launch.py
      #ARMA_CDLC=
      ARMA_CONFIG: "main2.cfg" #конфиг сервера
      ARMA_LIMITFPS: "100"
      ARMA_PARAMS: "-enableHT -cpuCount=6 -noSound -cfg=arma3\\configs\\basic2.cfg"
      ARMA_PROFILE: "server_wine" #имя профиля
      ARMA_WORLD: "empty"
      HEADLESS_CLIENTS: "2" #безголовые клиенты, закоментируй если не нужны
      HEADLESS_CLIENTS_PROFILE: "$profile-hc-$i" # valid placeholders: $profile, $i, $ii #безголовые клиенты, закоментируй если не нужны
      MODS_LOCAL: "true" #загрузит моды из папки /arma3/mods
      #MODS_PRESET: "/arma3/configs/anti_ult_test.html" #пресет с модами не работает без купленной армы
      PORT: "2402"
      STEAM_BRANCH: "public"
      STEAM_BRANCH_PASSWORD: ""

      #для скачивания сервера не нужно покупать арма3 нужен просто твинк
      STEAM_PASSWORD: "ChangeMe_PSWD" #пароль стим юзера
      STEAM_USER: "ChangeMe_STEAM_USER" #имя стим юзера

      #во время самого первого запуска нужно притормозить (true) чтобы установить библитеки в вайн, потом пауза не нужна.
      PAUSE_START: true

      #timezone
      #TZ: "Africa/Tunis"
      
    restart: on-failure
    stdin_open: true
    tty: true

  novnc:  
      image: consol/ubuntu-icewm-vnc 
      environment:
          # Adjust to your screen size
          VNC_COL_DEPTH: "16"
          VNC_PW: "ChangeMe"
      volumes:
          #- /tmp/.X11-unix:/tmp/.X11-unix
          - /path/to/arma_server/tmp/.X11-unix:/tmp/.X11-unix
      ports:
          #- "127.0.0.1:6901:6901"
          - 6901:6901
          - 5901:5901
      user: 0:0
